name: CI

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set variables
      env:
        INPUT_TAG_NAME: ${{ github.ref }}
      run: |
        echo "::set-env MARKETING_VERSION=${INPUT_TAG_NAME:11}"
        echo "::set-env CURRENT_PROJECT_VERSION=$(git rev-list --count ${INPUT_TAG_NAME:10})"

    - name: Build
      id: build_archive
      run: |
        xcodebuild -resolvePackageDependencies -workspace LaunchXIV.xcworkspace -scheme LaunchXIV -clonedSourcePackagesDirPath ./Build
        xcodebuild archive -workspace LaunchXIV.xcworkspace -scheme LaunchXIV -clonedSourcePackagesDirPath ./Build -archivePath "./Build/LaunchXIV"
        cd Build
        ./MakeDMG.sh "LaunchXIV.xcarchive/Products/Applications/LaunchXIV.app"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./Build/LaunchXIV ${{ env.MARKETING_VERSION }}.dmg
        asset_name: LaunchXIV ${{ env.MARKETING_VERSION}}
        asset_content_type: application/x-apple-diskimage
